#!/bin/bash
if [ $# -ne 1 ]; then
    echo "Usage: $0 <number>"
    exit 1
fi

DAY=$1
echo "Running day$DAY"
cd "day$DAY" || { exit 1; }

FILE="main.cpp"

g++ "$FILE" -o output

if [ $? -ne 0 ]; then
    exit 1
fi

./output
rm ./output
